---
kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: logstash
  name: logstash
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: logstash
  ports:
  - port: 5044
    protocol: TCP
    targetPort: logstash
