---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: monitoring
spec:
  serviceName: elasticsearch
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: logging
      app.kubernetes.io/name: elasticsearch
  template:
    metadata:
      labels:
        app.kubernetes.io/component: logging
        app.kubernetes.io/name: elasticsearch
    spec:
      serviceAccountName: elasticsearch
      containers:
      - image: harbor.uat.enflame.cn/library/elasticsearch:6.8.15
        name: elasticsearch
        resources:
          limits:
            cpu: 8000m
            memory: 16Gi
          requests:
            cpu: 250m
            memory: 250Mi
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: cluster.name
          value: kubernetes-log
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.zen.ping.unicast.hosts
          value: "elasticsearch-0,elasticsearch-1"
        - name: discovery.zen.minimum_master_nodes
          value: "1"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        livenessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      initContainers:
      - image: harbor.uat.enflame.cn/library/alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-init
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 300Gi
      accessModes:
      - ReadWriteOnce