---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ui
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.python279.org
    http:
      paths:
      - backend:
          serviceName: grafana-service
          servicePort: 3000