---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
  name: grafana
  namespace: monitoring
spec:
  selector: 
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: grafana