---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: monitoring

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  namespace: monitoring
  name: elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch
  namespace: monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: elasticsearch
  apiGroup: ""