---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/component: logging
    app.kubernetes.io/name: elasticsearch
  clusterIP: None
  ports:
  - port: 9200
    protocol: TCP
