---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.1
  name: kube-state-metrics
  namespace: monitoring
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http-metrics
  - protocol: TCP
    port: 8081
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics