---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.1
  name: kube-state-metrics
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-rc.1
  ports:
  - port: 8080
    name: http-metrics
    protocol: TCP
    targetPort: http-metrics
  - port: 8081
    name: telemetry
    protocol: TCP
    targetPort: telemetry