{
 "title": "Enflame Monitor Dashboard",
 "description": "This dashboard is to display the metrics from Enflame Exporter on a Kubernetes cluster",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "节点",
    "query": {
     "query": "label_values(enflame_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DTU Power Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_power_usage{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}}"
    }
   ]
  },
  {
   "title": "DTU  Memory Size (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_memory_total_size_GB{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} (GB)"
    }
   ]
  },
  {
   "title": "DTU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_temperatures{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Clock (Hz)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_clock{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}} (Hz)"
    }
   ]
  },
  {
   "title": "DTU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_usage{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Avg Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(enflame_dtu_usage{instance=~\"^$node$\"}) by (instance, ID)",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_health{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Misc" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_state{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Heartbeat",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_heartbeat{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Ecc Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_ecc_status_enabled{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Current Reset Count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_current_reset_count{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Single Bit Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_ecc_status_single_bit_error{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Total Reset Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_total_reset_count{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Double Bit Error",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_ecc_status_double_bit_error{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU{{ID}}"
    }
   ]
  },
  {
   "title": "DTU Cluster Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_cluster_usage{instance=~\"^$node$\"}",
     "legendFormat": "Cluster{{Cluster}}"
    }
   ]
  },
  {
   "title": "DTU Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "enflame_dtu_count{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DTU ESL Throughput  (MB/S)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_esl_throughput_mbps{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} Port {{Port}} {{Metrics}} "
    }
   ]
  },
  {
   "title": "DTU ESL Nak/10ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_esl_nak_10ms{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} Port {{Port}} {{Metrics}}"
    }
   ]
  },
  {
   "title": "DTU ESL Link Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_esl_link_speed{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} Port {{Port}} {{Metrics}} "
    }
   ]
  },
  {
   "title": "DTU PCIE Link Width",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_pcie_link_width{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} {{Metrics}}"
    }
   ]
  },
  {
   "title": "DTU ESL Link",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_esl_link_info{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} Port {{Port}} {{Metrics}} "
    }
   ]
  },
  {
   "title": "DTU PCIE Link",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "enflame_dtu_pcie_link_info{instance=~\"^$node$\"}",
     "legendFormat": "{{instance}} / DTU {{ID}} {{Metrics}}"
    }
   ]
  }
 ]
}