---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-logging
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kibana.python279.org
    http:
      paths:
      - backend:
          serviceName: kibana-logging
          servicePort: 5601